spring:
  application:
    name: grabber-basic
  ai:
    ollama:
      embedding:
        enabled: false
      chat:
        model: llama3
        options:
          temperature: 0.9
      init:
        pull-model-strategy: always
        timeout: 15m
        max-retries: 2



server:
  port: 7070
